// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import "@openzeppelin/contracts/governance/Governor.sol";
import "@openzeppelin/contracts/governance/extensions/GovernorSettings.sol";
import "@openzeppelin/contracts/governance/extensions/GovernorCountingSimple.sol";
import "@openzeppelin/contracts/governance/extensions/GovernorVotes.sol";
import "@openzeppelin/contracts/governance/extensions/GovernorVotesQuorumFraction.sol";
import "@openzeppelin/contracts/governance/extensions/GovernorTimelockControl.sol";

/**
 * @title BaseLobsterGovernor
 * @dev Governance contract for BASE LOBSTER community decisions
 * Features:
 * - Create proposals for community decisions
 * - Three voting options: Yes (For), No (Against), Abstain
 * - Quorum: 10% of total supply must vote
 * - Voting period: 3 days
 * - Execution delay: 1 day after passing
 * - Full on-chain proposal history
 * 
 * Halal-compliant: No gambling, pure community governance
 */
contract BaseLobsterGovernor is
    Governor,
    GovernorSettings,
    GovernorCountingSimple,
    GovernorVotes,
    GovernorVotesQuorumFraction,
    GovernorTimelockControl
{
    /// @notice Events for proposal lifecycle
    event ProposalCreatedWithDescription(
        uint256 indexed proposalId,
        address indexed proposer,
        string description,
        uint256 startTime,
        uint256 endTime
    );

    /// @notice Proposal metadata storage
    struct ProposalMetadata {
        string title;
        string category;
        uint256 createdAt;
        bool isAIGenerated;
    }

    /// @notice Mapping from proposalId to metadata
    mapping(uint256 => ProposalMetadata) public proposalMetadata;

    /// @notice List of all proposal IDs for enumeration
    uint256[] public allProposalIds;

    /// @notice Categories for proposals
    string[] public proposalCategories = [
        "charity_donation",
        "community_event",
        "feature_request",
        "partnership_proposal",
        "governance_update",
        "treasury_allocation"
    ];

    /**
     * @dev Constructor sets up the governor with the token and timelock
     * @param _token The governance token (BaseLobsterToken)
     * @param _timelock The timelock controller for execution delay
     * 
     * Settings:
     * - Voting delay: 1 day (after proposal creation)
     * - Voting period: 3 days
     * - Proposal threshold: 0 (anyone with tokens can propose)
     * - Quorum: 10% of total supply
     */
    constructor(
        IVotes _token,
        TimelockController _timelock
    )
        Governor("BASE LOBSTER Governor")
        GovernorSettings(
            1 days,     // Voting delay: 1 day
            3 days,     // Voting period: 3 days
            0           // Proposal threshold: 0 tokens (anyone can propose)
        )
        GovernorVotes(_token)
        GovernorVotesQuorumFraction(10)  // 10% quorum
        GovernorTimelockControl(_timelock)
    {}

    /**
     * @dev Create a proposal with additional metadata
     * @param title Short title for the proposal
     * @param category Category of the proposal
     * @param isAIGenerated Whether this was generated by the AI bot
     * @param targets Contract addresses to call
     * @param values ETH values to send
     * @param calldatas Function call data
     * @param description Full proposal description
     */
    function proposeWithMetadata(
        string memory title,
        string memory category,
        bool isAIGenerated,
        address[] memory targets,
        uint256[] memory values,
        bytes[] memory calldatas,
        string memory description
    ) public returns (uint256) {
        uint256 proposalId = propose(targets, values, calldatas, description);
        
        proposalMetadata[proposalId] = ProposalMetadata({
            title: title,
            category: category,
            createdAt: block.timestamp,
            isAIGenerated: isAIGenerated
        });
        
        allProposalIds.push(proposalId);
        
        emit ProposalCreatedWithDescription(
            proposalId,
            msg.sender,
            description,
            proposalSnapshot(proposalId),
            proposalDeadline(proposalId)
        );
        
        return proposalId;
    }

    /**
     * @dev Get the count of all proposals
     */
    function getProposalCount() public view returns (uint256) {
        return allProposalIds.length;
    }

    /**
     * @dev Get proposal ID by index
     * @param index Index in the proposals array
     */
    function getProposalIdByIndex(uint256 index) public view returns (uint256) {
        require(index < allProposalIds.length, "Index out of bounds");
        return allProposalIds[index];
    }

    /**
     * @dev Get metadata for a proposal
     * @param proposalId The proposal ID
     */
    function getProposalMetadata(uint256 proposalId) public view returns (
        string memory title,
        string memory category,
        uint256 createdAt,
        bool isAIGenerated
    ) {
        ProposalMetadata storage meta = proposalMetadata[proposalId];
        return (meta.title, meta.category, meta.createdAt, meta.isAIGenerated);
    }

    // ============ Required Overrides ============

    function votingDelay()
        public
        view
        override(Governor, GovernorSettings)
        returns (uint256)
    {
        return super.votingDelay();
    }

    function votingPeriod()
        public
        view
        override(Governor, GovernorSettings)
        returns (uint256)
    {
        return super.votingPeriod();
    }

    function quorum(uint256 blockNumber)
        public
        view
        override(Governor, GovernorVotesQuorumFraction)
        returns (uint256)
    {
        return super.quorum(blockNumber);
    }

    function state(uint256 proposalId)
        public
        view
        override(Governor, GovernorTimelockControl)
        returns (ProposalState)
    {
        return super.state(proposalId);
    }

    function proposalNeedsQueuing(uint256 proposalId)
        public
        view
        override(Governor, GovernorTimelockControl)
        returns (bool)
    {
        return super.proposalNeedsQueuing(proposalId);
    }

    function proposalThreshold()
        public
        view
        override(Governor, GovernorSettings)
        returns (uint256)
    {
        return super.proposalThreshold();
    }

    function _queueOperations(
        uint256 proposalId,
        address[] memory targets,
        uint256[] memory values,
        bytes[] memory calldatas,
        bytes32 descriptionHash
    ) internal override(Governor, GovernorTimelockControl) returns (uint48) {
        return super._queueOperations(proposalId, targets, values, calldatas, descriptionHash);
    }

    function _executeOperations(
        uint256 proposalId,
        address[] memory targets,
        uint256[] memory values,
        bytes[] memory calldatas,
        bytes32 descriptionHash
    ) internal override(Governor, GovernorTimelockControl) {
        super._executeOperations(proposalId, targets, values, calldatas, descriptionHash);
    }

    function _cancel(
        address[] memory targets,
        uint256[] memory values,
        bytes[] memory calldatas,
        bytes32 descriptionHash
    ) internal override(Governor, GovernorTimelockControl) returns (uint256) {
        return super._cancel(targets, values, calldatas, descriptionHash);
    }

    function _executor()
        internal
        view
        override(Governor, GovernorTimelockControl)
        returns (address)
    {
        return super._executor();
    }
}
